<?php

// autoload_files.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    '567d3fc5d1c59415b649f2734fcacf9b' => $vendorDir . '/wordpress/abilities-api/includes/bootstrap.php',
);
