<?php
/**
 * This class manage the Abilities managed like Prompts
 *
 * @package BLU\Abilities
 */

namespace BLU\Abilities;

class Prompts {
	/**
	 * Constructor - registers WooCommerce product abilities if WooCommerce is active.
	 */
	public function __construct() {
		if ( ! class_exists( 'WooCommerce' ) ) {
			return;
		}

		$this->register_prompt_description();
		$this->register_prompt_categories();
		$this->register_prompt_tags();
		$this->register_prompt_brands();

	}

	/**
	 * Create a prompt to instruct the AI the steps to follow to suggest the long and short description
	 *
	 * @return void
	 */

	private function register_prompt_description() {
		blu_register_ability( 'blu/suggest-product-description', [
			'label'               => 'Suggest Product Description',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a description and a short description on product details',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'name'       => array(
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					),
					'categories' => array(
						'type'        => 'string',
						'description' => 'Category',
					),
					'tags'       => array(
						'type'        => 'string',
						'description' => 'Tags',
					),
				),
				'required'   => array( 'name' )
			),
			'execute_callback'    => function ( $input ) {
				$name        = $input['name'] ?? '';
				$instruction = include_once __DIR__ . '/../instructions/product-description-suggester.php';;

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					],
					[
						'categories'  => 'categories',
						'description' => 'Categories generated by `blu/suggest-product-categories`',
						'required'    => false
					],
					[
						'tags'        => 'tags',
						'description' => 'Tags generated by `blu/suggest-product-tag`',
						'required'    => false
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );
	}


	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the categories
	 *
	 * @return void
	 */
	private function register_prompt_categories() {
		blu_register_ability( 'blu/suggest-product-categories', [
			'label'               => 'Suggest Product Categories',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product categories based on product details',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'name' => array(
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					),
				),
				'required'   => array( 'name' )
			),
			'execute_callback'    => function ( $input ) {
				$product_name = $input['name'] ?? '';

				$instruction = include_once __DIR__ . '/../instructions/product-categories-suggester.php';


				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );

	}

	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the tag
	 *
	 * @return void
	 */
	private function register_prompt_tags() {
		blu_register_ability( 'blu/suggest-product-tag', [
			'label'               => 'Suggest Product Tag',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product tag based on product details',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'name'        => array(
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					),
					'description' => array(
						'type'        => 'string',
						'description' => 'Product description',
					),
					'categories' => array(
						'type'        => 'string',
						'description' => 'A comma separated product categories list',
					)
				),
				'required'   => array( 'name' )
			),
			'execute_callback'    => function ( $input ) {
				$name = $input['name'] ?? '';
				$desc = $input['description'] ?? '';
				$desc = !empty( $desc ) ? '.\n Here a short description for this product :'.$desc.'.\n' : '';
				$categories = !empty( $input['categories'] )  ? '\n The product has these categories :'.$input['categories']: '';
				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => "Generate SEO‑optimized tags for the product $name $desc $categories.\n 
												- Focus on keywords that improve search visibility and relevance. 
												- Limit the number of tags to between 5 and 7 items only. 
												- Do not include unrelated or generic terms.
												- Include both short‑tail and long‑tail keywords. 
												- Show the list as numeric list.
												- Consider product title, category, and context when generating tags
												- Ensure tags are product‑specific, customer‑oriented, and aligned with common search queries. 
												- Be sure to use existing tags if they apply
												- Require to customer to select one or more tag from it
												- Return the customer’s selection strictly as an array named `tags`. 
											Output format example:
												{
												  'tags': [
												    'tag1',
												    'tag2',
												    'tag3',
												  ]
												}
											",
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					],
					[
						'name'        => 'description',
						'description' => 'Product description',
						'required'    => false
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );
	}

	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the brand
	 *
	 * @return void
	 */
	private function register_prompt_brands() {
		blu_register_ability( 'blu/suggest-product-brand', [
			'label'               => 'Suggest Product Brands',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product brands based on product details',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'name'        => array(
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					),
					'description' => array(
						'type'        => 'string',
						'description' => 'Product description',
					)
				),
				'required'   => array( 'name' )
			),
			'execute_callback'    => function ( $input ) {
				$name = $input['name'] ?? '';
				$desc = $input['description'] ?? '';
				$desc = ! empty( $desc ) ? 'and these details :' . $desc : '';

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => "Generate SEO‑optimized brand references for the product $name $desc.\n 
												- Use only well‑known, relevant brands associated with this product category. 
												- Focus on brands that customers commonly search for in relation to this product. 
												- Limit the number of brands to between 3 and 5 items only. 
												- Do not invent or include non‑existent brands.
												- Require to customer to select one or more brand from it
												- Return the customer’s selection strictly as an array named `brands`. 
											Output format example:
												{
												  'brands': [
												    'brand1',
												    'brand2',
												    'brand3',
												  ]
												}
												",
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					],
					[
						'name'        => 'description',
						'description' => 'Product description',
						'required'    => false
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );
	}
}