<?php
/**
 * This class manage the Abilities managed like Prompts
 *
 * @package BLU\Abilities
 */

namespace BLU\Abilities;

class Prompts {
	/**
	 * Constructor - registers WooCommerce product abilities if WooCommerce is active.
	 */
	public function __construct() {
		if ( ! class_exists( 'WooCommerce' ) ) {
			return;
		}

		$this->register_improve_prompt_description();
		$this->register_prompt_description();
		$this->register_prompt_categories();
		$this->register_prompt_tags();
		$this->register_prompt_brands();
		$this->register_smart_product_prompt();
	}

	/**
	 * Create a prompt to instruct the AI the steps to follow to suggest the long and short description
	 *
	 * @return void
	 */

	private function register_prompt_description() {
		blu_register_ability( 'blu/suggest-product-description', [
			'label'               => 'Suggest Product Description',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a description and a short description on product details',
			'input_schema'        => [
				'type'       => 'object',
				'properties' => [
					'name'       => [
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					],
					'categories' => [
						'type'        => 'string',
						'description' => 'Category',
					],
					'tags'       => [
						'type'        => 'string',
						'description' => 'Tags',
					],
				],
				'required'   => [ 'name' ],
			],
			'execute_callback'    => function ( $input ) {
				$name        = $input['name'] ?? '';
				$instruction = include_once __DIR__ . '/../instructions/product-description-suggester.php';;

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9,
								],
							],
						],
					],
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true,
					],
					[
						'categories'  => 'categories',
						'description' => 'Categories generated by `blu/suggest-product-categories`',
						'required'    => false,
					],
					[
						'tags'        => 'tags',
						'description' => 'Tags generated by `blu/suggest-product-tag`',
						'required'    => false,
					],
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true,
				],
			],
		] );
	}


	/**
	 * Create a prompt to instruct the AI the steps to follow to improve the long and short description
	 *
	 * @return void
	 */

	private function register_improve_prompt_description() {
		blu_register_ability( 'blu/improve-product-description', [
			'label'               => 'Improve Product Description',
			'category'            => 'blu-mcp',
			'description'         => 'Improve the existing description and short description for a product',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'id'       => array(
						'type'        => 'integer',
						'description' => 'Product ID.',
					),
					'tone' => array(
						'type'        => 'string',
						'description' => 'User tone.',
						'enum'        => array( 'formal', 'technical', 'empathetic', 'persuasive' ),
						'default'     => 'formal',
					)
				),
				'required'   => array( 'id' )
			),
			'execute_callback'    => function ( $input ) {

			$product = wc_get_product( $input['id'] );
			$tone = $input['tone'] ?? 'formal';
			$name = $product->get_title();
			$description = $product->get_description();
			$short_description = $product->get_short_description();
			$instruction = include_once __DIR__ . '/../instructions/product-description-improvement.php';

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					],
					[
						'categories'  => 'categories',
						'description' => 'Categories generated by `blu/suggest-product-categories`',
						'required'    => false
					],
					[
						'tags'        => 'tags',
						'description' => 'Tags generated by `blu/suggest-product-tag`',
						'required'    => false
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );
	}

	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the categories
	 *
	 * @return void
	 */
	private function register_prompt_categories() {
		blu_register_ability( 'blu/suggest-product-categories', [
			'label'               => 'Suggest Product Categories',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product categories based on product details',
			'input_schema'        => [
				'type'       => 'object',
				'properties' => [
					'name' => [
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					],
				],
				'required'   => [ 'name' ],
			],
			'execute_callback'    => function ( $input ) {
				$product_name = $input['name'] ?? '';

				$instruction = include_once __DIR__ . '/../instructions/product-categories-suggester.php';


				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9,
								],
							],
						],
					],
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true,
					],
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true,
				],
			],
		] );

	}

	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the tag
	 *
	 * @return void
	 */
	private function register_prompt_tags() {
		blu_register_ability( 'blu/suggest-product-tag', [
			'label'               => 'Suggest Product Tag',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product tag based on product details',
			'input_schema'        => [
				'type'       => 'object',
				'properties' => [
					'name'        => [
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					],
					'description' => [
						'type'        => 'string',
						'description' => 'Product description',
					],
					'categories'  => [
						'type'        => 'string',
						'description' => 'A comma separated product categories list',
					],
				],
				'required'   => [ 'name' ],
			],
			'execute_callback'    => function ( $input ) {
				$product_name       = $input['name'] ?? '';
				$product_desc       = $input['description'] ?? '';
				$product_desc       = ! empty( $product_desc ) ? '.\n Here a short description for this product :' . $product_desc . '.\n' : '';
				$product_categories = ! empty( $input['categories'] ) ? '\n The product has these categories :' . $input['categories'] : '';

				$instruction = include_once __DIR__ . '/../instructions/product-tags-suggester.php';

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9,
								],
							],
						],
					],
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true,
					],
					[
						'name'        => 'description',
						'description' => 'Product description',
						'required'    => false,
					],
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true,
				],
			],
		] );
	}

	/**
	 * Create a prompt to instruct the AI the step to follow to suggest the brand
	 *
	 * @return void
	 */
	private function register_prompt_brands() {
		blu_register_ability( 'blu/suggest-product-brand', [
			'label'               => 'Suggest Product Brands',
			'category'            => 'blu-mcp',
			'description'         => 'Generate a list of product brands based on product details',
			'input_schema'        => [
				'type'       => 'object',
				'properties' => [
					'name'        => [
						'type'        => 'string',
						'description' => 'Product name',
						'default'     => '',
					],
					'description' => [
						'type'        => 'string',
						'description' => 'Product description',
					],
				],
				'required'   => [ 'name' ],
			],
			'execute_callback'    => function ( $input ) {
				$name = $input['name'] ?? '';
				$desc = $input['description'] ?? '';
				$desc = ! empty( $desc ) ? 'and these details :' . $desc : '';

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => "Generate SEO‑optimized brand references for the product $name $desc.\n 
												- Use only well‑known, relevant brands associated with this product category. 
												- Focus on brands that customers commonly search for in relation to this product. 
												- Limit the number of brands to between 3 and 5 items only. 
												- Do not invent or include non‑existent brands.
												- Require to customer to select one or more brand from it
												- Return the customer’s selection strictly as an array named `brands`. 
											Output format example:
												{
												  'brands': [
												    'brand1',
												    'brand2',
												    'brand3',
												  ]
												}
												",
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9,
								],
							],
						],
					],
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true,
					],
					[
						'name'        => 'description',
						'description' => 'Product description',
						'required'    => false,
					],
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true,
				],
			],
		] );
	}


	private function register_smart_product_prompt(){
		blu_register_ability( 'blu/smart-product-details', [
			'label'               => 'Merchant Content Intelligence Generator',
			'category'            => 'blu-mcp',
			'description'         => 'A compact all‑in‑one prompt for merchants that uses the product ID and basic product details to automatically generate all key listing content — required materials, size charts, care instructions, warranty info, and ingredient lists — ensuring every product page is complete and compliant.',
			'input_schema'        => array(
				'type'       => 'object',
				'properties' => array(
					'id'       => array(
						'type'        => 'integer',
						'description' => 'Product ID.',
					),
				),
				'required'   => array( 'id' )
			),
			'execute_callback'    => function ( $input ) {

				$product = wc_get_product( $input['id'] );
				$name = $product->get_title();
				$description = $product->get_description();
				$categories = wc_get_product_category_list( $product->get_id() );
				$tags = wc_get_product_tag_list( $product->get_id() );
				$instruction = include_once __DIR__ . '/../instructions/smart-product-details.php';

				return [
					'messages' => [
						[
							'role'    => 'user',
							'content' => [
								'type'        => 'text',
								'text'        => $instruction,
								'annotations' => [
									'audience' => [ 'assistant' ],
									'priority' => 0.9
								]
							]
						]
					]
				];
			},
			'permission_callback' => function () {
				return current_user_can( 'edit_posts' );
			},
			'meta'                => [
				'arguments'   => [
					[
						'name'        => 'name',
						'description' => 'Product name to check',
						'required'    => true
					],
					[
						'categories'  => 'categories',
						'description' => 'Categories generated by `blu/suggest-product-categories`',
						'required'    => false
					],
					[
						'tags'        => 'tags',
						'description' => 'Tags generated by `blu/suggest-product-tag`',
						'required'    => false
					]
				],
				'annotations' => [
					'readOnlyHint'   => true,
					'idempotentHint' => true
				]
			]
		] );
	}
}